services:
  paracron:
    image: alpine:3.20
    container_name: paracron

    restart: unless-stopped

    command: /bin/sh /entrypoint.sh

    environment:
      MYSQL_BACKUP_PW: ${MYSQL_BACKUP_PW}

    networks:
      internal:
        ipv4_address: 172.28.0.13


    volumes:
      - ./entrypoint.sh:/entrypoint.sh:ro
      - ./custom:/custom:ro
      - paracron_data:/data

volumes:
  paracron_data:
