name: paradise
include:
  # Nginx Proxy Manager
  - services/nginx_proxy_manager/docker-compose.yaml
  # IP2ASN Helper
  - services/ip2asn/docker-compose.yaml
  # Valkey
  - services/valkey/docker-compose.yaml
networks:
  # We are statically allocating IPs to ensure they never change. This lets us sidestep issues with DNS caching
  # 0.1: gateway
  # 0.2: nginx
  # 0.3: ip2asn
  # 0.4: valkey
  internal:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1
