name: paradise
include:
  # Alice - internal only, comment out if youre a public dev
  - services/alice/docker-compose.yaml
  # Authentik
  - services/authentik/docker-compose.yaml
  # BAB
  - services/bab/docker-compose.yaml
  # CC Exporter
  - services/cc_exporter/docker-compose.yaml
  # ForumDaemon - internal only, comment out if youre a public dev
  - services/forumdaemon/docker-compose.yaml
  # IP2ASN Helper
  - services/ip2asn/docker-compose.yaml
  # MariaDB
  - services/mariadb/docker-compose.yaml
  # MediaWiki
  - services/mediawiki/docker-compose.yaml
  # Nginx Proxy Manager
  - services/nginx_proxy_manager/docker-compose.yaml
  # ParaCron
  - services/paracron/docker-compose.yaml
  # Postgres
  - services/postgres/docker-compose.yaml
  # Public API
  - services/public_api/docker-compose.yaml
  # Taskdaemon
  - services/taskdaemon/docker-compose.yaml
  # Valkey
  - services/valkey/docker-compose.yaml
  # YTDLP
  - services/ytdlp/docker-compose.yaml
networks:
  # We are statically allocating IPs to ensure they never change. This lets us sidestep issues with DNS caching
  # 0.1:  gateway
  # 0.2:  nginxpm        80    81   443
  # 0.3:  ip2asn      53661
  # 0.4:  valkey       6379
  # 0.5:  ytdlp       33432
  # 0.6:  taskdaemon
  # 0.7:  cc_exporter  6659
  # 0.8:  public_api  32314
  # 0.9:  postgres     5432
  # 0.10: alice
  # 0.11: auth server  9000
  # 0.12: auth worker
  # 0.13: paracron
  # 0.14: mariadb      3306
  # 0.15: mw core      9100
  # 0.16: mw nginx     9200
  # 0.17: forumdaemon  6434
  # 0.18: bab          8181
  internal:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1
