services:
  public_api:
    image: docker-public.paradisestation.org/paradise/public-api:20260808.145926-bc6ecc3
    container_name: public_api
    restart: unless-stopped

    ports:
      - "32314:32314"

    networks:
      internal:
        ipv4_address: 172.28.0.8

    configs:
      - source: publicapi_appsettings
        target: /app/appsettings.json

configs:
  publicapi_appsettings:
    file: ./appsettings.json
