services:
  ytdlp:
    image: docker-public.paradisestation.org/absolucy/ss13-yt-wrap:20260802.190334-bb69136
    container_name: ytdlp
    restart: unless-stopped
    ports:
      - "33432:33432"

    environment:
      - YTDLP_PORT=33432

    networks:
      internal:
        ipv4_address: 172.28.0.5
