services:
  mediawiki_core:
    image: docker-public.paradisestation.org/paradise/parawiki:20260809.191144-1286416
    container_name: mediawiki_core
    restart: unless-stopped
    volumes:
      - ./LocalSettings.php:/var/www/html/LocalSettings.php:ro
      - mediawiki-images:/var/www/html/images

    networks:
      internal:
        ipv4_address: 172.28.0.15

  mediawiki_nginx:
    image: nginx:1.30.4-trixie
    container_name: mediawiki_nginx
    restart: unless-stopped

    ports:
      - "9200:9200"

    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - mediawiki-images:/var/www/html/images:ro

    depends_on:
      - mediawiki_core

    networks:
      internal:
        ipv4_address: 172.28.0.16

volumes:
  mediawiki-images:
