server {
    listen 9200;
    server_name _;

    root /var/www/html;
    index index.php index.html index.htm;

    # Root dir - should never be hit
    location / {
        try_files $uri $uri/ @mediawiki;
    }

    # Handle MW rewrite rules
    location ^~ /wiki/ {
        # Rewrites /wiki/index.php, /wiki/api.php, etc. -> /index.php, /api.php
        rewrite ^/wiki/(.+\.php)$ /$1 last;

        # Rewrites legacy static asset paths -> /skins/, /resources/, etc.
        rewrite ^/wiki/(skins|resources|images|extensions)/(.*)$ /$1/$2 last;

        # Short URL rewrite (/wiki/Main_Page -> /index.php?title=Main_Page)
        rewrite ^/wiki/(?<pagename>.*)$ /index.php?title=$pagename last;
    }

    # Serve statics directly
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        expires 30d;
        add_header Cache-Control "public, no-transform";
        log_not_found off;
        access_log off;
        try_files $uri =404;
    }

    # Handle direct things like /Main_Page
    location @mediawiki {
        rewrite ^/(.*)$ /index.php?title=$1 last;
    }

    # Prevent execution of uploaded scripts
    location ^~ /images/ {
        location ~ \.php$ {
            deny all;
        }
    }

    # Pass PHP requests to mediawiki_core container
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_param REQUEST_URI $uri$is_args$args;
        fastcgi_param HTTP_X_FORWARDED_FOR $http_cf_connecting_ip;
        
        fastcgi_pass 172.28.0.15:9100;
    }
}