services:
  tools_nginx:
    image: docker-public.paradisestation.org/paradise/paraphp:20260831.202458-464e6d9
    container_name: tools_nginx
    restart: unless-stopped

    ports:
      - "8081:8080"

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - toolsnginx-webroot:/var/www/html
      - /mnt/espresso_logs:/mnt/espresso_logs:ro
      - /mnt/espresso_assets:/mnt/espresso_assets:ro

    networks:
      internal:
        ipv4_address: 172.28.0.19

volumes:
  toolsnginx-webroot:
