services:
  taskdaemon:
    image: docker-public.paradisestation.org/paradise/taskdaemon:20260824.203329-fc64089
    container_name: taskdaemon
    restart: unless-stopped
    networks:
      internal:
        ipv4_address: 172.28.0.6

    configs:
      - source: taskdaemon
        target: /app/config.toml

configs:
  taskdaemon:
    file: ./config.toml
